services:

  postgres:
    image: postgres:13
    container_name: hospitaldb
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hospital_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2-alpine
    container_name: hospitalredis
    ports:
      - "6379:6379"

  auth-service:
    build:
      context: ../services/auth-service
    container_name: auth-service
    ports:
      - "8083:8083"
    environment:
      - SERVER_PORT=8083
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/hospital_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - postgres

  patients-service:
    build:
      context: ../services/patients-service
    container_name: patients-service
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/hospital_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - postgres

  scheduling-service:
    build:
      context: ../services/scheduling-service
    container_name: scheduling-service
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8082
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/hospital_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATA_REDIS_HOST=redis
      - PATIENT_SERVICE_URL=http://patients-service:8081/patients
    depends_on:
      - postgres
      - redis

  # Novo serviço adicionado
  inventory-service:
    build:
      context: ../services/inventory-service
    container_name: inventory-service
    ports:
      - "8086:8086"
    environment:
      - SERVER_PORT=8086
      # Note a alteração de 'localhost' para 'postgres' na URL
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/hospital_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - postgres

  gateway-service:
    build:
      context: ../services/gateway-service
    container_name: gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - patients-service
      - scheduling-service
      - auth-service
      - inventory-service

volumes:
  postgres_data: